version: '3.4'
services:
  app:
    image: ambientum/php:7.2-nginx
    container_name: server-app
    ports:
      - 80:8080
    volumes:
      - .:/var/www/app
    links:
      - mariadb
      - redis
    networks:
      - server

  mariadb:
    image: mariadb:10.3
    container_name: server-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: server
      MYSQL_DATABASE: server
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    volumes:
      - server-mariadb:/var/lib/mariadb
    networks:
      - server

  redis:
    image: redis:4.0.8-alpine
    container_name: server-redis
    command: --appendonly yes
    volumes:
      - server-redis:/data
    ports:
      - 6379:6379
    networks:
      - server

  selenium:
    image: selenium/standalone-chrome
    container_name: server-selenium
    networks:
      - server

  horizon:
    image: ambientum/php:7.2
    container_name: server-horizon
    command: php artisan horizon
    volumes:
      - .:/var/www/app
    depends_on:
      - redis
    links:
      - mariadb
      - redis
    networks:
      - server

networks:
  server:
    driver: bridge
volumes:
  server-mariadb:
    driver: local
  server-redis:
    driver: local
